
# genome to be used
genome: hg38_noalt

# location of genome, needs to be set
genome_dir: /shared/sudlab1/General/mirror/genomes/index

#STREME#
# options, see streme --help
e_value: 0.1
#For the moment hard encoded,max possible is 8
min_motif_width: 6
max_motif_width: 12

#HOMER#
# options, see findMotifs.pl --help
motif_sizes: 6,8,10,12
#FDR threshold
fdr: 0.1
#N° of iteration for FDR
FDRiteration: 100

#FIRE#
#Does 6 and 7 kmers automaticallym but 8 kmers only for small sets
8kmer: 0

#Tomtom#
#Merging motif files#
#q-value threshold for scanning redundant motifs from streme, homer and fire out
thresh_self: 0.1
#q-value threshold for merging motifs files together
thresh_merge: 0.1

#Tomtom comparison of final list of motifs to remove similar motifs in highstab
#and 1lowstab
#q-value threshold for tomtom
thresh_final: 0.1

#Extract sequences from meme PWM
#If only the consensus sequence of the motif has to be extracted, then no
#option is necessary, if several need to be extracted from one motif (based on
#icscore, see universal vignette), then add option '-l'
options: ''
#Full path to miRNA seeds in meme  format
mirna_seeds_db: /shared/sudlab1/General/mirror/meme_motif_db/motif_databases/MIRBASE/22/Homo_sapiens_hsa.seeds.meme
# O or 1, if 1 miRNA seeds are filtered for relevant miRNA detected in A549 and HepG2 cells
filter_mirna: 1
#File for filtering
relevant_mirna: /mnt/sharc/shared/sudlab1/General/projects/SynthUTR_hepG2_a549/miRmine/relevant_miRNA_a549_hepg2.tsv
