
# genome to be used
genome: hg38_noalt

# location of genome, needs to be set (indexing will be done with slamdunk map)
genome_dir: /shared/sudlab1/General/mirror/genomes/index

#STREME#
# options, see streme --help
p_value: 0.05
min_motif_width: 8
max_motif_width: 15
patience: 3

#HOMER#
# options, see findMotifs.pl --help
motif_sizes: 8,10,12,15
