
# genome to be used
genome: hg38_noalt

# location of genome, needs to be set
genome_dir: /shared/sudlab1/General/mirror/genomes/index

#STREME#
# options, see streme --help
e_value: 0.1
#For the moment hard encoded,max possible is 8
min_motif_width: 6
max_motif_width: 12

#HOMER#
# options, see findMotifs.pl --help
motif_sizes: 6,8,10,12
fdr: 0.1

#FIRE#
kmer_sizes: 6,7,8 #For the moment hard encoded,max possible is 8

#Tomtom#
#Merging motif files#
#q-value threshold for scanning redundant motifs from streme, homer and fire out
thresh_self: 0.1
#q-value threshold for merging motifs files together
thresh_merge: 0.1

#Scanning for miRNA seeds in motifs
#Full path of miRNA seeds database in meme format
mirna_db: /shared/sudlab1/General/mirror/meme_motif_db/motif_databases/MIRBASE/22/Homo_sapiens_hsa.meme
#q-value threshold for tomtom
thresh_mirna: 0.5
